<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_about',
		'title' => 'About',
		'fields' => array (
			array (
				'key' => 'field_53230a5d1a526',
				'label' => 'Team',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53230aa91a527',
				'label' => 'Team Members',
				'name' => 'team_members',
				'type' => 'repeater',
				'instructions' => 'Add members',
				'sub_fields' => array (
					array (
						'key' => 'field_53230ae91a528',
						'label' => 'Full Name',
						'name' => 'full_name',
						'type' => 'text',
						'instructions' => 'Add the full name',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53230b151a529',
						'label' => 'Position',
						'name' => 'position',
						'type' => 'text',
						'instructions' => 'Add the position of the memeber',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53230b361a52a',
						'label' => 'Social Networks',
						'name' => 'social_networks',
						'type' => 'repeater',
						'instructions' => 'Add social networks to the team member',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53230b511a52b',
								'label' => 'Network',
								'name' => 'network',
								'type' => 'select',
								'instructions' => 'Select the network',
								'column_width' => '',
								'choices' => array (
									'fa-apple' => 'apple',
									'fa-android' => 'android',
									'fa-flickr' => 'flickr',
									'fa-facebook' => 'facebook',
									'fa-foursquare' => 'foursquare',
									'fa-google-plus' => 'google plus',
									'fa-dribbble' => 'dribbble',
									'fa-linkedin' => 'linkedin',
									'fa-pinterest' => 'pinterest',
									'fa-tumblr' => 'tumblr',
									'fa-youtube' => 'youtube',
									'fa-twitter' => 'twitter',
									'fa-vimeo-square' => 'vimeo',
									'fa-skype' => 'skype',
									'fa-windows' => 'windows',
									'fa-instagram' => 'instagram',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53230c0e1a52c',
								'label' => 'Network Url',
								'name' => 'network_url',
								'type' => 'text',
								'instructions' => 'Add the network url',
								'column_width' => '',
								'default_value' => 'http://',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Network',
					),
					array (
						'key' => 'field_53230c231a52d',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => 'Add the description of the team member',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_53230c3e1a52e',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add an image to the team member',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Member',
			),
			array (
				'key' => 'field_53230c681a52f',
				'label' => 'Facts',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53230c741a530',
				'label' => 'Facts',
				'name' => 'facts',
				'type' => 'repeater',
				'instructions' => 'Add facts to the page',
				'sub_fields' => array (
					array (
						'key' => 'field_53230c901a531',
						'label' => 'Fact Name',
						'name' => 'fact_name',
						'type' => 'text',
						'instructions' => 'Add the fact name',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53230cbe1a532',
						'label' => 'Fact Description',
						'name' => 'fact_description',
						'type' => 'text',
						'instructions' => 'Add a short description to the fact',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53230ccd1a533',
						'label' => 'Fact Icon',
						'name' => 'fact_icon',
						'type' => 'select',
						'instructions' => 'Select the icon',
						'column_width' => '',
						'choices' => array (
							'none' => 'none',
							'fa-glass' => '&#xf000;',
							'fa-music' => '&#xf001;',
							'fa-search' => '&#xf002;',
							'fa-envelope-o' => '&#xf003;',
							'fa-heart' => '&#xf004;',
							'fa-star' => '&#xf005;',
							'fa-star-o' => '&#xf006;',
							'fa-user' => '&#xf007;',
							'fa-film' => '&#xf008;',
							'fa-th-large' => '&#xf009;',
							'fa-th' => '&#xf00a;',
							'fa-th-list' => '&#xf00b;',
							'fa-check' => '&#xf00c;',
							'fa-times' => '&#xf00d;',
							'fa-search-plus' => '&#xf00e;',
							'fa-search-minus' => '&#xf010;',
							'fa-power-off' => '&#xf011;',
							'fa-signal' => '&#xf012;',
							'fa-cog' => '&#xf013;',
							'fa-trash-o' => '&#xf014;',
							'fa-home' => '&#xf015;',
							'fa-file-o' => '&#xf016;',
							'fa-clock-o' => '&#xf017;',
							'fa-road' => '&#xf018;',
							'fa-download' => '&#xf019;',
							'fa-arrow-circle-o-down' => '&#xf01a;',
							'fa-arrow-circle-o-up' => '&#xf01b;',
							'fa-inbox' => '&#xf01c;',
							'fa-play-circle-o' => '&#xf01d;',
							'fa-repeat' => '&#xf01e;',
							'fa-refresh' => '&#xf021;',
							'fa-list-alt' => '&#xf022;',
							'fa-lock' => '&#xf023;',
							'fa-flag' => '&#xf024;',
							'fa-headphones' => '&#xf025;',
							'fa-volume-off' => '&#xf026;',
							'fa-volume-down' => '&#xf027;',
							'fa-volume-up' => '&#xf028;',
							'fa-qrcode' => '&#xf029;',
							'fa-barcode' => '&#xf02a;',
							'fa-tag' => '&#xf02b;',
							'fa-tags' => '&#xf02c;',
							'fa-book' => '&#xf02d;',
							'fa-bookmark' => '&#xf02e;',
							'fa-print' => '&#xf02f;',
							'fa-camera' => '&#xf030;',
							'fa-font' => '&#xf031;',
							'fa-bold' => '&#xf032;',
							'fa-italic' => '&#xf033;',
							'fa-text-height' => '&#xf034;',
							'fa-text-width' => '&#xf035;',
							'fa-align-left' => '&#xf036;',
							'fa-align-center' => '&#xf037;',
							'fa-align-right' => '&#xf038;',
							'fa-align-justify' => '&#xf039;',
							'fa-list' => '&#xf03a;',
							'fa-outdent' => '&#xf03b;',
							'fa-indent' => '&#xf03c;',
							'fa-video-camera' => '&#xf03d;',
							'fa-picture-o' => '&#xf03e;',
							'fa-pencil' => '&#xf040;',
							'fa-map-marker' => '&#xf041;',
							'fa-adjust' => '&#xf042;',
							'fa-tint' => '&#xf043;',
							'fa-pencil-square-o' => '&#xf044;',
							'fa-share-square-o' => '&#xf045;',
							'fa-check-square-o' => '&#xf046;',
							'fa-arrows' => '&#xf047;',
							'fa-step-backward' => '&#xf048;',
							'fa-fast-backward' => '&#xf049;',
							'fa-backward' => '&#xf04a;',
							'fa-play' => '&#xf04b;',
							'fa-pause' => '&#xf04c;',
							'fa-stop' => '&#xf04d;',
							'fa-forward' => '&#xf04e;',
							'fa-fast-forward' => '&#xf050;',
							'fa-step-forward' => '&#xf051;',
							'fa-eject' => '&#xf052;',
							'fa-chevron-left' => '&#xf053;',
							'fa-chevron-right' => '&#xf054;',
							'fa-plus-circle' => '&#xf055;',
							'fa-minus-circle' => '&#xf056;',
							'fa-times-circle' => '&#xf057;',
							'fa-check-circle' => '&#xf058;',
							'fa-question-circle' => '&#xf059;',
							'fa-info-circle' => '&#xf05a;',
							'fa-crosshairs' => '&#xf05b;',
							'fa-times-circle-o' => '&#xf05c;',
							'fa-check-circle-o' => '&#xf05d;',
							'fa-ban' => '&#xf05e;',
							'fa-arrow-left' => '&#xf060;',
							'fa-arrow-right' => '&#xf061;',
							'fa-arrow-up' => '&#xf062;',
							'fa-arrow-down' => '&#xf063;',
							'fa-share' => '&#xf064;',
							'fa-expand' => '&#xf065;',
							'fa-compress' => '&#xf066;',
							'fa-plus' => '&#xf067;',
							'fa-minus' => '&#xf068;',
							'fa-asterisk' => '&#xf069;',
							'fa-exclamation-circle' => '&#xf06a;',
							'fa-gift' => '&#xf06b;',
							'fa-leaf' => '&#xf06c;',
							'fa-fire' => '&#xf06d;',
							'fa-eye' => '&#xf06e;',
							'fa-eye-slash' => '&#xf070;',
							'fa-exclamation-triangle' => '&#xf071;',
							'fa-plane' => '&#xf072;',
							'fa-calendar' => '&#xf073;',
							'fa-random' => '&#xf074;',
							'fa-comment' => '&#xf075;',
							'fa-magnet' => '&#xf076;',
							'fa-chevron-up' => '&#xf077;',
							'fa-chevron-down' => '&#xf078;',
							'fa-retweet' => '&#xf079;',
							'fa-shopping-cart' => '&#xf07a;',
							'fa-folder' => '&#xf07b;',
							'fa-folder-open' => '&#xf07c;',
							'fa-arrows-v' => '&#xf07d;',
							'fa-arrows-h' => '&#xf07e;',
							'fa-bar-chart-o' => '&#xf080;',
							'fa-twitter-square' => '&#xf081;',
							'fa-facebook-square' => '&#xf082;',
							'fa-camera-retro' => '&#xf083;',
							'fa-key' => '&#xf084;',
							'fa-cogs' => '&#xf085;',
							'fa-comments' => '&#xf086;',
							'fa-thumbs-o-up' => '&#xf087;',
							'fa-thumbs-o-down' => '&#xf088;',
							'fa-star-half' => '&#xf089;',
							'fa-heart-o' => '&#xf08a;',
							'fa-sign-out' => '&#xf08b;',
							'fa-linkedin-square' => '&#xf08c;',
							'fa-thumb-tack' => '&#xf08d;',
							'fa-external-link' => '&#xf08e;',
							'fa-sign-in' => '&#xf090;',
							'fa-trophy' => '&#xf091;',
							'fa-github-square' => '&#xf092;',
							'fa-upload' => '&#xf093;',
							'fa-lemon-o' => '&#xf094;',
							'fa-phone' => '&#xf095;',
							'fa-square-o' => '&#xf096;',
							'fa-bookmark-o' => '&#xf097;',
							'fa-phone-square' => '&#xf098;',
							'fa-twitter' => '&#xf099;',
							'fa-facebook' => '&#xf09a;',
							'fa-github' => '&#xf09b;',
							'fa-unlock' => '&#xf09c;',
							'fa-credit-card' => '&#xf09d;',
							'fa-rss' => '&#xf09e;',
							'fa-hdd-o' => '&#xf0a0;',
							'fa-bullhorn' => '&#xf0a1;',
							'fa-bell' => '&#xf0f3;',
							'fa-certificate' => '&#xf0a3;',
							'fa-hand-o-right' => '&#xf0a4;',
							'fa-hand-o-left' => '&#xf0a5;',
							'fa-hand-o-up' => '&#xf0a6;',
							'fa-hand-o-down' => '&#xf0a7;',
							'fa-arrow-circle-left' => '&#xf0a8;',
							'fa-arrow-circle-right' => '&#xf0a9;',
							'fa-arrow-circle-up' => '&#xf0aa;',
							'fa-arrow-circle-down' => '&#xf0ab;',
							'fa-globe' => '&#xf0ac;',
							'fa-wrench' => '&#xf0ad;',
							'fa-tasks' => '&#xf0ae;',
							'fa-filter' => '&#xf0b0;',
							'fa-briefcase' => '&#xf0b1;',
							'fa-arrows-alt' => '&#xf0b2;',
							'fa-users' => '&#xf0c0;',
							'fa-link' => '&#xf0c1;',
							'fa-cloud' => '&#xf0c2;',
							'fa-flask' => '&#xf0c3;',
							'fa-scissors' => '&#xf0c4;',
							'fa-files-o' => '&#xf0c5;',
							'fa-paperclip' => '&#xf0c6;',
							'fa-floppy-o' => '&#xf0c7;',
							'fa-square' => '&#xf0c8;',
							'fa-bars' => '&#xf0c9;',
							'fa-list-ul' => '&#xf0ca;',
							'fa-list-ol' => '&#xf0cb;',
							'fa-strikethrough' => '&#xf0cc;',
							'fa-underline' => '&#xf0cd;',
							'fa-table' => '&#xf0ce;',
							'fa-magic' => '&#xf0d0;',
							'fa-truck' => '&#xf0d1;',
							'fa-pinterest' => '&#xf0d2;',
							'fa-pinterest-square' => '&#xf0d3;',
							'fa-google-plus-square' => '&#xf0d4;',
							'fa-google-plus' => '&#xf0d5;',
							'fa-money' => '&#xf0d6;',
							'fa-caret-down' => '&#xf0d7;',
							'fa-caret-up' => '&#xf0d8;',
							'fa-caret-left' => '&#xf0d9;',
							'fa-caret-right' => '&#xf0da;',
							'fa-columns' => '&#xf0db;',
							'fa-sort' => '&#xf0dc;',
							'fa-sort-asc' => '&#xf0dd;',
							'fa-sort-desc' => '&#xf0de;',
							'fa-envelope' => '&#xf0e0;',
							'fa-linkedin' => '&#xf0e1;',
							'fa-undo' => '&#xf0e2;',
							'fa-gavel' => '&#xf0e3;',
							'fa-tachometer' => '&#xf0e4;',
							'fa-comment-o' => '&#xf0e5;',
							'fa-comments-o' => '&#xf0e6;',
							'fa-bolt' => '&#xf0e7;',
							'fa-sitemap' => '&#xf0e8;',
							'fa-umbrella' => '&#xf0e9;',
							'fa-clipboard' => '&#xf0ea;',
							'fa-lightbulb-o' => '&#xf0eb;',
							'fa-exchange' => '&#xf0ec;',
							'fa-cloud-download' => '&#xf0ed;',
							'fa-cloud-upload' => '&#xf0ee;',
							'fa-user-md' => '&#xf0f0;',
							'fa-stethoscope' => '&#xf0f1;',
							'fa-suitcase' => '&#xf0f2;',
							'fa-bell-o' => '&#xf0a2;',
							'fa-coffee' => '&#xf0f4;',
							'fa-cutlery' => '&#xf0f5;',
							'fa-file-text-o' => '&#xf0f6;',
							'fa-building-o' => '&#xf0f7;',
							'fa-hospital-o' => '&#xf0f8;',
							'fa-ambulance' => '&#xf0f9;',
							'fa-medkit' => '&#xf0fa;',
							'fa-fighter-jet' => '&#xf0fb;',
							'fa-beer' => '&#xf0fc;',
							'fa-h-square' => '&#xf0fd;',
							'fa-plus-square' => '&#xf0fe;',
							'fa-angle-double-left' => '&#xf100;',
							'fa-angle-double-right' => '&#xf101;',
							'fa-angle-double-up' => '&#xf102;',
							'fa-angle-double-down' => '&#xf103;',
							'fa-angle-left' => '&#xf104;',
							'fa-angle-right' => '&#xf105;',
							'fa-angle-up' => '&#xf106;',
							'fa-angle-down' => '&#xf107;',
							'fa-desktop' => '&#xf108;',
							'fa-laptop' => '&#xf109;',
							'fa-tablet' => '&#xf10a;',
							'fa-mobile' => '&#xf10b;',
							'fa-circle-o' => '&#xf10c;',
							'fa-quote-left' => '&#xf10d;',
							'fa-quote-right' => '&#xf10e;',
							'fa-spinner' => '&#xf110;',
							'fa-circle' => '&#xf111;',
							'fa-reply' => '&#xf112;',
							'fa-github-alt' => '&#xf113;',
							'fa-folder-o' => '&#xf114;',
							'fa-folder-open-o' => '&#xf115;',
							'fa-smile-o' => '&#xf118;',
							'fa-frown-o' => '&#xf119;',
							'fa-meh-o' => '&#xf11a;',
							'fa-gamepad' => '&#xf11b;',
							'fa-keyboard-o' => '&#xf11c;',
							'fa-flag-o' => '&#xf11d;',
							'fa-flag-checkered' => '&#xf11e;',
							'fa-terminal' => '&#xf120;',
							'fa-code' => '&#xf121;',
							'fa-reply-all' => '&#xf122;',
							'fa-mail-reply-all' => '&#xf122;',
							'fa-star-half-o' => '&#xf123;',
							'fa-location-arrow' => '&#xf124;',
							'fa-crop' => '&#xf125;',
							'fa-code-fork' => '&#xf126;',
							'fa-chain-broken' => '&#xf127;',
							'fa-question' => '&#xf128;',
							'fa-info' => '&#xf129;',
							'fa-exclamation' => '&#xf12a;',
							'fa-superscript' => '&#xf12b;',
							'fa-subscript' => '&#xf12c;',
							'fa-eraser' => '&#xf12d;',
							'fa-puzzle-piece' => '&#xf12e;',
							'fa-microphone' => '&#xf130;',
							'fa-microphone-slash' => '&#xf131;',
							'fa-shield' => '&#xf132;',
							'fa-calendar-o' => '&#xf133;',
							'fa-fire-extinguisher' => '&#xf134;',
							'fa-rocket' => '&#xf135;',
							'fa-maxcdn' => '&#xf136;',
							'fa-chevron-circle-left' => '&#xf137;',
							'fa-chevron-circle-right' => '&#xf138;',
							'fa-chevron-circle-up' => '&#xf139;',
							'fa-chevron-circle-down' => '&#xf13a;',
							'fa-html5' => '&#xf13b;',
							'fa-css3' => '&#xf13c;',
							'fa-anchor' => '&#xf13d;',
							'fa-unlock-alt' => '&#xf13e;',
							'fa-bullseye' => '&#xf140;',
							'fa-ellipsis-h' => '&#xf141;',
							'fa-ellipsis-v' => '&#xf142;',
							'fa-rss-square' => '&#xf143;',
							'fa-play-circle' => '&#xf144;',
							'fa-ticket' => '&#xf145;',
							'fa-minus-square' => '&#xf146;',
							'fa-minus-square-o' => '&#xf147;',
							'fa-level-up' => '&#xf148;',
							'fa-level-down' => '&#xf149;',
							'fa-check-square' => '&#xf14a;',
							'fa-pencil-square' => '&#xf14b;',
							'fa-external-link-square' => '&#xf14c;',
							'fa-share-square' => '&#xf14d;',
							'fa-compass' => '&#xf14e;',
							'fa-caret-square-o-down' => '&#xf150;',
							'fa-caret-square-o-up' => '&#xf151;',
							'fa-caret-square-o-right' => '&#xf152;',
							'fa-eur' => '&#xf153;',
							'fa-gbp' => '&#xf154;',
							'fa-usd' => '&#xf155;',
							'fa-inr' => '&#xf156;',
							'fa-jpy' => '&#xf157;',
							'fa-rub' => '&#xf158;',
							'fa-krw' => '&#xf159;',
							'fa-btc' => '&#xf15a;',
							'fa-file' => '&#xf15b;',
							'fa-file-text' => '&#xf15c;',
							'fa-sort-alpha-asc' => '&#xf15d;',
							'fa-sort-alpha-desc' => '&#xf15e;',
							'fa-sort-amount-asc' => '&#xf160;',
							'fa-sort-amount-desc' => '&#xf161;',
							'fa-sort-numeric-asc' => '&#xf162;',
							'fa-sort-numeric-desc' => '&#xf163;',
							'fa-thumbs-up' => '&#xf164;',
							'fa-thumbs-down' => '&#xf165;',
							'fa-youtube-square' => '&#xf166;',
							'fa-youtube' => '&#xf167;',
							'fa-xing' => '&#xf168;',
							'fa-xing-square' => '&#xf169;',
							'fa-youtube-play' => '&#xf16a;',
							'fa-dropbox' => '&#xf16b;',
							'fa-stack-overflow' => '&#xf16c;',
							'fa-instagram' => '&#xf16d;',
							'fa-flickr' => '&#xf16e;',
							'fa-adn' => '&#xf170;',
							'fa-bitbucket' => '&#xf171;',
							'fa-bitbucket-square' => '&#xf172;',
							'fa-tumblr' => '&#xf173;',
							'fa-tumblr-square' => '&#xf174;',
							'fa-long-arrow-down' => '&#xf175;',
							'fa-long-arrow-up' => '&#xf176;',
							'fa-long-arrow-left' => '&#xf177;',
							'fa-long-arrow-right' => '&#xf178;',
							'fa-apple' => '&#xf179;',
							'fa-windows' => '&#xf17a;',
							'fa-android' => '&#xf17b;',
							'fa-linux' => '&#xf17c;',
							'fa-dribbble' => '&#xf17d;',
							'fa-skype' => '&#xf17e;',
							'fa-foursquare' => '&#xf180;',
							'fa-trello' => '&#xf181;',
							'fa-female' => '&#xf182;',
							'fa-male' => '&#xf183;',
							'fa-gittip' => '&#xf184;',
							'fa-sun-o' => '&#xf185;',
							'fa-moon-o' => '&#xf186;',
							'fa-archive' => '&#xf187;',
							'fa-bug' => '&#xf188;',
							'fa-vk' => '&#xf189;',
							'fa-weibo' => '&#xf18a;',
							'fa-renren' => '&#xf18b;',
							'fa-pagelines' => '&#xf18c;',
							'fa-stack-exchange' => '&#xf18d;',
							'fa-arrow-circle-o-right' => '&#xf18e;',
							'fa-arrow-circle-o-left' => '&#xf190;',
							'fa-caret-square-o-left' => '&#xf191;',
							'fa-dot-circle-o' => '&#xf192;',
							'fa-wheelchair' => '&#xf193;',
							'fa-vimeo-square' => '&#xf194;',
							'fa-try' => '&#xf195;',
							'fa-plus-square-o' => '&#xf196;',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_533d74bef17fc',
						'label' => 'Fact Link',
						'name' => 'fact_link',
						'type' => 'text',
						'instructions' => 'Add an external link to the fact',
						'column_width' => '',
						'default_value' => 'http://',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Fact',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_audio-post',
		'title' => 'Audio Post',
		'fields' => array (
			array (
				'key' => 'field_5342a96e361ce',
				'label' => 'Audio Artist',
				'name' => 'audio_artist',
				'type' => 'text',
				'instructions' => 'Add the artist of the song',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53231b7d3ca9f',
				'label' => 'Audio Title',
				'name' => 'audio_title',
				'type' => 'text',
				'instructions' => 'Add the audio title',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53231af83ca9c',
				'label' => 'Audio Type',
				'name' => 'audio_type',
				'type' => 'radio',
				'instructions' => 'Choose the type of audio',
				'choices' => array (
					'url' => 'Url',
					'selfHost' => 'Self Hosted',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'url',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53231b233ca9d',
				'label' => 'Url',
				'name' => 'url',
				'type' => 'text',
				'instructions' => 'Add the url for the audio',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53231af83ca9c',
							'operator' => '==',
							'value' => 'url',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53231b583ca9e',
				'label' => 'Audio File',
				'name' => 'audio_file',
				'type' => 'file',
				'instructions' => 'Add the audio file',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53231af83ca9c',
							'operator' => '==',
							'value' => 'selfHost',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'audio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog',
		'title' => 'BLog',
		'fields' => array (
			array (
				'key' => 'field_53208f3171f36',
				'label' => 'Categories',
				'name' => 'categories',
				'type' => 'radio',
				'instructions' => 'Display all categories or custom categories',
				'choices' => array (
					'all' => 'All',
					'custom' => 'Custom',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'all',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53208f9f71f37',
				'label' => 'Custom Categories',
				'name' => 'custom_categories',
				'type' => 'taxonomy',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53208f3171f36',
							'operator' => '==',
							'value' => 'custom',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-blog_big.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-blog_buckets.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_clients',
		'title' => 'Clients',
		'fields' => array (
			array (
				'key' => 'field_531f15506e210',
				'label' => 'Clients',
				'name' => 'clients',
				'type' => 'repeater',
				'instructions' => 'Add clients',
				'sub_fields' => array (
					array (
						'key' => 'field_531f15a86e214',
						'label' => 'Client logo',
						'name' => 'client_logo',
						'type' => 'image',
						'instructions' => 'Add the client logo',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_531f15636e211',
						'label' => 'Client Name',
						'name' => 'client_name',
						'type' => 'text',
						'instructions' => 'Add the client name',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_531f15816e212',
						'label' => 'Client Link',
						'name' => 'client_link',
						'type' => 'text',
						'instructions' => 'Add the client link',
						'column_width' => '',
						'default_value' => 'http://',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_531f15916e213',
						'label' => 'Client short description',
						'name' => 'client_short_description',
						'type' => 'textarea',
						'instructions' => 'Add the client short descrition',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'formatting' => 'br',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Client',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-clients.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact',
		'title' => 'Contact',
		'fields' => array (
			array (
				'key' => 'field_5321b84e78f0f',
				'label' => 'Map',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5321b86478f10',
				'label' => 'Google Map',
				'name' => 'google_map',
				'type' => 'googlemap',
				'instructions' => 'Set location',
			),
			array (
				'key' => 'field_5321b87f78f11',
				'label' => 'Zoom level',
				'name' => 'zoom_level',
				'type' => 'number',
				'instructions' => 'Choose the zoom level<br>
	<b>Avalible levels from 0 to 19</b>',
				'default_value' => 15,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 19,
				'step' => '',
			),
			array (
				'key' => 'field_532c28f50c26b',
				'label' => 'Disable Zoom in',
				'name' => 'disable_zoom_in',
				'type' => 'true_false',
				'instructions' => 'Disable zoom in/out when users scroll',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5321b91578f12',
				'label' => 'Custom Marker',
				'name' => 'custom_marker',
				'type' => 'image',
				'instructions' => 'Add your custom marker',
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5321bbac69bd8',
				'label' => 'Disable Map',
				'name' => 'disable_map',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5321b93e78f13',
				'label' => 'Details',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5321b95378f14',
				'label' => 'Details',
				'name' => 'details',
				'type' => 'repeater',
				'instructions' => 'Add details',
				'sub_fields' => array (
					array (
						'key' => 'field_5321b97778f15',
						'label' => 'Detail Title',
						'name' => 'detail_title',
						'type' => 'text',
						'instructions' => 'Add the title',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5321b98278f16',
						'label' => 'Detail Content',
						'name' => 'detail_content',
						'type' => 'wysiwyg',
						'instructions' => 'Add the content',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Detail',
			),
			array (
				'key' => 'field_5321b9a078f17',
				'label' => 'Contact Form',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5321ba4a78f1d',
				'label' => 'Email Receiver',
				'name' => 'email_receiver',
				'type' => 'text',
				'instructions' => 'Add the receivers email<br>
	<b>If its blank, email will go to admins email</b>',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321b9b978f18',
				'label' => 'Contact Form Name',
				'name' => 'contact_form_name',
				'type' => 'text',
				'instructions' => 'Add the contact form name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321b9e778f19',
				'label' => 'Contact Form Slogan',
				'name' => 'contact_form_slogan',
				'type' => 'text',
				'instructions' => 'Add the contact form slogan',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321ba0b78f1a',
				'label' => 'Name Label',
				'name' => 'name_label',
				'type' => 'text',
				'instructions' => 'Add the name label',
				'default_value' => 'Name',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321ba2978f1b',
				'label' => 'Email Label',
				'name' => 'email_label',
				'type' => 'text',
				'instructions' => 'Add the email label',
				'default_value' => 'Email',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321c1ca6b826',
				'label' => 'Message Label',
				'name' => 'message_label',
				'type' => 'text',
				'instructions' => 'Add the message label',
				'default_value' => 'Message',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321ba3878f1c',
				'label' => 'Send Button Label',
				'name' => 'send_button_label',
				'type' => 'text',
				'instructions' => 'Add the send button label',
				'default_value' => 'Send',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321baa978f1e',
				'label' => 'Success Message',
				'name' => 'success_message',
				'type' => 'text',
				'instructions' => 'Add the success mesage',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5321bab978f1f',
				'label' => 'Fail Message ',
				'name' => 'fail_message',
				'type' => 'text',
				'instructions' => 'Add the fail message',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_footer',
		'title' => 'Footer',
		'fields' => array (
			array (
				'key' => 'field_532c2b609a228',
				'label' => 'Footer Content',
				'name' => 'footer_content',
				'type' => 'wysiwyg',
				'instructions' => 'Add the footer content',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_532c2b9c9a229',
				'label' => 'Social Networks',
				'name' => 'social_networks',
				'type' => 'repeater',
				'instructions' => 'Add social networks',
				'sub_fields' => array (
					array (
						'key' => 'field_532c2baf9a22a',
						'label' => 'Network',
						'name' => 'network',
						'type' => 'select',
						'instructions' => 'Select the social network',
						'column_width' => '',
						'choices' => array (
							'fa-apple' => 'apple',
							'fa-android' => 'android',
							'fa-flickr' => 'flickr',
							'fa-facebook' => 'facebook',
							'fa-foursquare' => 'foursquare',
							'fa-google-plus' => 'google plus',
							'fa-dribbble' => 'dribbble',
							'fa-linkedin' => 'linkedin',
							'fa-pinterest' => 'pinterest',
							'fa-tumblr' => 'tumblr',
							'fa-youtube' => 'youtube',
							'fa-twitter' => 'twitter',
							'fa-vimeo-square' => 'vimeo',
							'fa-skype' => 'skype',
							'fa-windows' => 'windows',
							'fa-instagram' => 'instagram',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_532c2bdc9a22b',
						'label' => 'Network Url',
						'name' => 'network_url',
						'type' => 'text',
						'instructions' => 'Add the social network link',
						'column_width' => '',
						'default_value' => 'http://',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Network',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-footer',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_galleries-template',
		'title' => 'Galleries Template',
		'fields' => array (
			array (
				'key' => 'field_5314d17a9ccc5',
				'label' => 'Categories',
				'name' => 'categories',
				'type' => 'radio',
				'instructions' => 'Display all categories or custom categories',
				'choices' => array (
					'all' => 'All',
					'custom' => 'Custom',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'all',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5314d1ac9ccc6',
				'label' => 'Custom categories',
				'name' => 'custom_categories',
				'type' => 'taxonomy',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5314d17a9ccc5',
							'operator' => '==',
							'value' => 'custom',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'gallery_category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-galleries_showcase.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-gallerys_hrisontal.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-gallery_bucket.php',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_gallery',
		'title' => 'Gallery',
		'fields' => array (
			array (
				'key' => 'field_53298a34c55a2',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53298996c559f',
				'label' => 'Slider Type',
				'name' => 'slider_type',
				'type' => 'radio',
				'instructions' => 'Choose type of slider',
				'choices' => array (
					'standard' => 'Standard',
					'bg' => 'With Background Image',
					'pattern' => 'Pattern',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'standard',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_532989d6c55a0',
				'label' => 'Image',
				'name' => 'background_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53298996c559f',
							'operator' => '==',
							'value' => 'bg',
						),
						array (
							'field' => 'field_53298996c559f',
							'operator' => '==',
							'value' => 'pattern',
						),
					),
					'allorany' => 'any',
				),
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53298a0ec55a1',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'gallery',
				'preview_size' => 'thumbnail',
			),
			array (
				'key' => 'field_53298a41c55a3',
				'label' => 'Other Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53298a4ec55a4',
				'label' => 'Post details',
				'name' => 'post_details',
				'type' => 'repeater',
				'instructions' => 'Add details',
				'sub_fields' => array (
					array (
						'key' => 'field_53298a66c55a5',
						'label' => 'Detail Title',
						'name' => 'detail_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53298a6ec55a6',
						'label' => 'Details Content',
						'name' => 'details_content',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Detail',
			),
			array (
				'key' => 'field_53298a83c55a7',
				'label' => 'Disable Network Share',
				'name' => 'disable_network_share',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'gallery_post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_header',
		'title' => 'Header',
		'fields' => array (
			array (
				'key' => 'field_530f4efcaef89',
				'label' => 'Logo Type',
				'name' => 'logo_type',
				'type' => 'radio',
				'instructions' => 'Choose the logo type',
				'choices' => array (
					'text' => 'Text',
					'image' => 'Image',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_530f4f5caef8a',
				'label' => 'Logo Text',
				'name' => 'logo_text',
				'type' => 'text',
				'instructions' => 'Add the text logo',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_530f4efcaef89',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530f4f83aef8b',
				'label' => 'Logo Color',
				'name' => 'logo_color',
				'type' => 'color_picker',
				'instructions' => 'Add the color for the logo',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_530f4efcaef89',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#000000',
			),
			array (
				'key' => 'field_530f4fa0aef8c',
				'label' => 'Logo Size',
				'name' => 'logo_size',
				'type' => 'number',
				'instructions' => 'Add the logo size',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_530f4efcaef89',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 100,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 200,
				'step' => '',
			),
			array (
				'key' => 'field_530f4fd8aef8d',
				'label' => 'Logo Font',
				'name' => 'logo_font',
				'type' => 'googlefonts',
				'instructions' => 'Choose the font for the logo',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_530f4efcaef89',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_530f5002aef8e',
				'label' => 'Logo Image',
				'name' => 'logo_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_530f4efcaef89',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_530f5013aef8f',
				'label' => 'Retina Logo',
				'name' => 'retina_logo',
				'type' => 'true_false',
				'instructions' => 'Allow to display the logo in retina',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_530f4efcaef89',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_530f5038aef90',
				'label' => 'Web Site Slogan',
				'name' => 'web_site_slogan',
				'type' => 'wysiwyg',
				'instructions' => 'Add the slogan',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_530f507753f08',
				'label' => 'Site Favicon',
				'name' => 'site_favicon',
				'type' => 'image',
				'instructions' => 'Add the favicon for the site',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-header',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-minimal',
		'title' => 'Home Minimal',
		'fields' => array (
			array (
				'key' => 'field_531f19a25c3fd',
				'label' => 'Slider Effect',
				'name' => 'slider_effect',
				'type' => 'radio',
				'instructions' => 'Choose the effect of the slider',
				'choices' => array (
					'fade' => 'Fade',
					'slide' => 'Slide',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'fade',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_531f1a255c3fe',
				'label' => 'Slider Auto Play',
				'name' => 'slider_auto_play',
				'type' => 'true_false',
				'instructions' => 'Slide through images automatically',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_531f1a7c5c3ff',
				'label' => 'Slider',
				'name' => 'slider',
				'type' => 'repeater',
				'instructions' => 'Add slides',
				'sub_fields' => array (
					array (
						'key' => 'field_531f1a9d5c400',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add the image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_531f1aad5c401',
						'label' => 'Image Overlay color',
						'name' => 'image_overlay_color',
						'type' => 'color_picker',
						'instructions' => 'Choose the overlay color',
						'column_width' => '',
						'default_value' => '#000000',
					),
					array (
						'key' => 'field_531f1acb5c402',
						'label' => 'Image Overlay Percantage',
						'name' => 'image_overlay_percantage',
						'type' => 'number',
						'instructions' => 'Add the number in percantage',
						'column_width' => '',
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => 100,
						'step' => '',
					),
					array (
						'key' => 'field_531f1b7e5c403',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'wysiwyg',
						'instructions' => 'Add the content in the slider',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_531f1ba15c404',
						'label' => 'Content effect',
						'name' => 'content_effect',
						'type' => 'select',
						'instructions' => 'Select the effect',
						'column_width' => '',
						'choices' => array (
							'none' => 'none',
							'flash' => 'flash',
							'bounce' => 'bounce',
							'shake' => 'shake',
							'tada' => 'tada',
							'swing' => 'swing',
							'wobble' => 'wobble',
							'pulse' => 'pulse',
							'flip' => 'flip',
							'flipInX' => 'flipInX',
							'flipInY' => 'flipInY',
							'fadeIn' => 'fadeIn',
							'fadeInUp' => 'fadeInUp',
							'fadeInDown' => 'fadeInDown',
							'fadeInLeft' => 'fadeInLeft',
							'fadeInRight' => 'fadeInRight',
							'fadeInUpBig' => 'fadeInUpBig',
							'fadeInDownBig' => 'fadeInDownBig',
							'fadeInLeftBig' => 'fadeInLeftBig',
							'fadeInRightBig' => 'fadeInRightBig',
							'bounceIn' => 'bounceIn',
							'bounceInDown' => 'bounceInDown',
							'bounceInUp' => 'bounceInUp',
							'bounceInLeft' => 'bounceInLeft',
							'bounceInRight' => 'bounceInRight',
							'rotateIn' => 'rotateIn',
							'rotateInDownLeft' => 'rotateInDownLeft',
							'rotateInDownRight' => 'rotateInDownRight',
							'rotateInUpLeft' => 'rotateInUpLeft',
							'rotateInUpRight' => 'rotateInUpRight',
							'lightSpeedIn' => 'lightSpeedIn',
							'rollIn' => 'rollIn',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_531f1c9e5c405',
						'label' => 'Button Text',
						'name' => 'button_text',
						'type' => 'text',
						'instructions' => 'Add the button text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_531f1cab5c406',
						'label' => 'Button Link',
						'name' => 'button_link',
						'type' => 'text',
						'instructions' => 'Add the button link',
						'column_width' => '',
						'default_value' => 'http://',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_531f1cb85c407',
						'label' => 'Button effect',
						'name' => 'button_effect',
						'type' => 'select',
						'instructions' => 'Select the button effect',
						'column_width' => '',
						'choices' => array (
							'none' => 'none',
							'flash' => 'flash',
							'bounce' => 'bounce',
							'shake' => 'shake',
							'tada' => 'tada',
							'swing' => 'swing',
							'wobble' => 'wobble',
							'pulse' => 'pulse',
							'flip' => 'flip',
							'flipInX' => 'flipInX',
							'flipInY' => 'flipInY',
							'fadeIn' => 'fadeIn',
							'fadeInUp' => 'fadeInUp',
							'fadeInDown' => 'fadeInDown',
							'fadeInLeft' => 'fadeInLeft',
							'fadeInRight' => 'fadeInRight',
							'fadeInUpBig' => 'fadeInUpBig',
							'fadeInDownBig' => 'fadeInDownBig',
							'fadeInLeftBig' => 'fadeInLeftBig',
							'fadeInRightBig' => 'fadeInRightBig',
							'bounceIn' => 'bounceIn',
							'bounceInDown' => 'bounceInDown',
							'bounceInUp' => 'bounceInUp',
							'bounceInLeft' => 'bounceInLeft',
							'bounceInRight' => 'bounceInRight',
							'rotateIn' => 'rotateIn',
							'rotateInDownLeft' => 'rotateInDownLeft',
							'rotateInDownRight' => 'rotateInDownRight',
							'rotateInUpLeft' => 'rotateInUpLeft',
							'rotateInUpRight' => 'rotateInUpRight',
							'lightSpeedIn' => 'lightSpeedIn',
							'rollIn' => 'rollIn',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Slide',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-minimal.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-showcase',
		'title' => 'Home Showcase',
		'fields' => array (
			array (
				'key' => 'field_5314bd98a0e71',
				'label' => 'Display Type',
				'name' => 'display_type',
				'type' => 'radio',
				'instructions' => 'Choose how to display galleries',
				'choices' => array (
					'cat' => 'By Category',
					'custom' => 'Custom',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'cat',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5314be63a0e72',
				'label' => 'Categories',
				'name' => 'categories',
				'type' => 'taxonomy',
				'instructions' => 'Choose the categories that you want to display',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5314bd98a0e71',
							'operator' => '==',
							'value' => 'cat',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'gallery_category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5314bea1a0e73',
				'label' => 'Custom Slelection',
				'name' => 'custom_slelection',
				'type' => 'relationship',
				'instructions' => 'Choose the galleries that you want to display',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5314bd98a0e71',
							'operator' => '==',
							'value' => 'custom',
						),
					),
					'allorany' => 'all',
				),
				'return_format' => 'object',
				'post_type' => array (
					0 => 'gallery_post',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-showcase.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_image-post',
		'title' => 'Image Post',
		'fields' => array (
			array (
				'key' => 'field_53231aa4435fc',
				'label' => 'Image',
				'name' => 'add_image',
				'type' => 'image',
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'image',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_main',
		'title' => 'Main',
		'fields' => array (
			array (
				'key' => 'field_5314d318a84a0',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5344067dd961b',
				'label' => 'Menus',
				'name' => 'menus',
				'type' => 'radio',
				'instructions' => 'Choose a menu',
				'choices' => array (
					'vertical' => 'Vertical',
					'horizontal' => 'Horizontal',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'vertical',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5314d31fa84a1',
				'label' => 'Disable ajax',
				'name' => 'disable_ajax',
				'type' => 'true_false',
				'instructions' => 'Check to disable ajax',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_532b042ae58b1',
				'label' => 'Disable Loading',
				'name' => 'disable_loading',
				'type' => 'true_false',
				'instructions' => 'Check to disable loading bar for the site',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53298ca10bf0a',
				'label' => 'Share Galleries in',
				'name' => 'share_galleries_in',
				'type' => 'checkbox',
				'instructions' => 'Check the social networks for sharing galleries',
				'choices' => array (
					'facebook' => 'Facebook',
					'twitter' => 'Twitter',
					'google' => 'Google+',
					'pinit' => 'Pin it',
					'linkedIn' => 'Linked In',
					'stumble' => 'Stumble Upon',
				),
				'default_value' => 'facebook
	twitter
	google
	pinit
	linkedIn
	stumble',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53319d9224775',
				'label' => 'Branding',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53319da124776',
				'label' => 'Brand Color',
				'name' => 'brand_color',
				'type' => 'color_picker',
				'instructions' => 'Choose the brand color',
				'default_value' => '#f41e1e',
			),
			array (
				'key' => 'field_53319dd324777',
				'label' => 'Website Font',
				'name' => 'website_font',
				'type' => 'googlefonts',
				'instructions' => 'Select the website font',
			),
			array (
				'key' => 'field_53319e1724778',
				'label' => 'Custom Code',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53319e1f24779',
				'label' => 'Custom Css',
				'name' => 'custom_css',
				'type' => 'textarea',
				'instructions' => 'Add custom css',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_53319e5b2477a',
				'label' => 'Custom Java-script',
				'name' => 'custom_java-script',
				'type' => 'textarea',
				'instructions' => 'Add custom java-script',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-main',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page',
		'title' => 'Page',
		'fields' => array (
			array (
				'key' => 'field_5332eb5832b5f',
				'label' => 'Enable Sidebar',
				'name' => 'enable_sidebar',
				'type' => 'true_false',
				'instructions' => 'Check to enable sidebar on the default page',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_services',
		'title' => 'Services',
		'fields' => array (
			array (
				'key' => 'field_531f05d02a6d3',
				'label' => 'Services',
				'name' => 'services',
				'type' => 'repeater',
				'instructions' => 'Add the services',
				'sub_fields' => array (
					array (
						'key' => 'field_531f0a0f2a6d5',
						'label' => 'Service Icon',
						'name' => 'service_icon',
						'type' => 'select',
						'instructions' => 'Choose the icon',
						'column_width' => '',
						'choices' => array (
							'none' => 'none',
							'fa-glass' => '&#xf000;',
							'fa-music' => '&#xf001;',
							'fa-search' => '&#xf002;',
							'fa-envelope-o' => '&#xf003;',
							'fa-heart' => '&#xf004;',
							'fa-star' => '&#xf005;',
							'fa-star-o' => '&#xf006;',
							'fa-user' => '&#xf007;',
							'fa-film' => '&#xf008;',
							'fa-th-large' => '&#xf009;',
							'fa-th' => '&#xf00a;',
							'fa-th-list' => '&#xf00b;',
							'fa-check' => '&#xf00c;',
							'fa-times' => '&#xf00d;',
							'fa-search-plus' => '&#xf00e;',
							'fa-search-minus' => '&#xf010;',
							'fa-power-off' => '&#xf011;',
							'fa-signal' => '&#xf012;',
							'fa-cog' => '&#xf013;',
							'fa-trash-o' => '&#xf014;',
							'fa-home' => '&#xf015;',
							'fa-file-o' => '&#xf016;',
							'fa-clock-o' => '&#xf017;',
							'fa-road' => '&#xf018;',
							'fa-download' => '&#xf019;',
							'fa-arrow-circle-o-down' => '&#xf01a;',
							'fa-arrow-circle-o-up' => '&#xf01b;',
							'fa-inbox' => '&#xf01c;',
							'fa-play-circle-o' => '&#xf01d;',
							'fa-repeat' => '&#xf01e;',
							'fa-refresh' => '&#xf021;',
							'fa-list-alt' => '&#xf022;',
							'fa-lock' => '&#xf023;',
							'fa-flag' => '&#xf024;',
							'fa-headphones' => '&#xf025;',
							'fa-volume-off' => '&#xf026;',
							'fa-volume-down' => '&#xf027;',
							'fa-volume-up' => '&#xf028;',
							'fa-qrcode' => '&#xf029;',
							'fa-barcode' => '&#xf02a;',
							'fa-tag' => '&#xf02b;',
							'fa-tags' => '&#xf02c;',
							'fa-book' => '&#xf02d;',
							'fa-bookmark' => '&#xf02e;',
							'fa-print' => '&#xf02f;',
							'fa-camera' => '&#xf030;',
							'fa-font' => '&#xf031;',
							'fa-bold' => '&#xf032;',
							'fa-italic' => '&#xf033;',
							'fa-text-height' => '&#xf034;',
							'fa-text-width' => '&#xf035;',
							'fa-align-left' => '&#xf036;',
							'fa-align-center' => '&#xf037;',
							'fa-align-right' => '&#xf038;',
							'fa-align-justify' => '&#xf039;',
							'fa-list' => '&#xf03a;',
							'fa-outdent' => '&#xf03b;',
							'fa-indent' => '&#xf03c;',
							'fa-video-camera' => '&#xf03d;',
							'fa-picture-o' => '&#xf03e;',
							'fa-pencil' => '&#xf040;',
							'fa-map-marker' => '&#xf041;',
							'fa-adjust' => '&#xf042;',
							'fa-tint' => '&#xf043;',
							'fa-pencil-square-o' => '&#xf044;',
							'fa-share-square-o' => '&#xf045;',
							'fa-check-square-o' => '&#xf046;',
							'fa-arrows' => '&#xf047;',
							'fa-step-backward' => '&#xf048;',
							'fa-fast-backward' => '&#xf049;',
							'fa-backward' => '&#xf04a;',
							'fa-play' => '&#xf04b;',
							'fa-pause' => '&#xf04c;',
							'fa-stop' => '&#xf04d;',
							'fa-forward' => '&#xf04e;',
							'fa-fast-forward' => '&#xf050;',
							'fa-step-forward' => '&#xf051;',
							'fa-eject' => '&#xf052;',
							'fa-chevron-left' => '&#xf053;',
							'fa-chevron-right' => '&#xf054;',
							'fa-plus-circle' => '&#xf055;',
							'fa-minus-circle' => '&#xf056;',
							'fa-times-circle' => '&#xf057;',
							'fa-check-circle' => '&#xf058;',
							'fa-question-circle' => '&#xf059;',
							'fa-info-circle' => '&#xf05a;',
							'fa-crosshairs' => '&#xf05b;',
							'fa-times-circle-o' => '&#xf05c;',
							'fa-check-circle-o' => '&#xf05d;',
							'fa-ban' => '&#xf05e;',
							'fa-arrow-left' => '&#xf060;',
							'fa-arrow-right' => '&#xf061;',
							'fa-arrow-up' => '&#xf062;',
							'fa-arrow-down' => '&#xf063;',
							'fa-share' => '&#xf064;',
							'fa-expand' => '&#xf065;',
							'fa-compress' => '&#xf066;',
							'fa-plus' => '&#xf067;',
							'fa-minus' => '&#xf068;',
							'fa-asterisk' => '&#xf069;',
							'fa-exclamation-circle' => '&#xf06a;',
							'fa-gift' => '&#xf06b;',
							'fa-leaf' => '&#xf06c;',
							'fa-fire' => '&#xf06d;',
							'fa-eye' => '&#xf06e;',
							'fa-eye-slash' => '&#xf070;',
							'fa-exclamation-triangle' => '&#xf071;',
							'fa-plane' => '&#xf072;',
							'fa-calendar' => '&#xf073;',
							'fa-random' => '&#xf074;',
							'fa-comment' => '&#xf075;',
							'fa-magnet' => '&#xf076;',
							'fa-chevron-up' => '&#xf077;',
							'fa-chevron-down' => '&#xf078;',
							'fa-retweet' => '&#xf079;',
							'fa-shopping-cart' => '&#xf07a;',
							'fa-folder' => '&#xf07b;',
							'fa-folder-open' => '&#xf07c;',
							'fa-arrows-v' => '&#xf07d;',
							'fa-arrows-h' => '&#xf07e;',
							'fa-bar-chart-o' => '&#xf080;',
							'fa-twitter-square' => '&#xf081;',
							'fa-facebook-square' => '&#xf082;',
							'fa-camera-retro' => '&#xf083;',
							'fa-key' => '&#xf084;',
							'fa-cogs' => '&#xf085;',
							'fa-comments' => '&#xf086;',
							'fa-thumbs-o-up' => '&#xf087;',
							'fa-thumbs-o-down' => '&#xf088;',
							'fa-star-half' => '&#xf089;',
							'fa-heart-o' => '&#xf08a;',
							'fa-sign-out' => '&#xf08b;',
							'fa-linkedin-square' => '&#xf08c;',
							'fa-thumb-tack' => '&#xf08d;',
							'fa-external-link' => '&#xf08e;',
							'fa-sign-in' => '&#xf090;',
							'fa-trophy' => '&#xf091;',
							'fa-github-square' => '&#xf092;',
							'fa-upload' => '&#xf093;',
							'fa-lemon-o' => '&#xf094;',
							'fa-phone' => '&#xf095;',
							'fa-square-o' => '&#xf096;',
							'fa-bookmark-o' => '&#xf097;',
							'fa-phone-square' => '&#xf098;',
							'fa-twitter' => '&#xf099;',
							'fa-facebook' => '&#xf09a;',
							'fa-github' => '&#xf09b;',
							'fa-unlock' => '&#xf09c;',
							'fa-credit-card' => '&#xf09d;',
							'fa-rss' => '&#xf09e;',
							'fa-hdd-o' => '&#xf0a0;',
							'fa-bullhorn' => '&#xf0a1;',
							'fa-bell' => '&#xf0f3;',
							'fa-certificate' => '&#xf0a3;',
							'fa-hand-o-right' => '&#xf0a4;',
							'fa-hand-o-left' => '&#xf0a5;',
							'fa-hand-o-up' => '&#xf0a6;',
							'fa-hand-o-down' => '&#xf0a7;',
							'fa-arrow-circle-left' => '&#xf0a8;',
							'fa-arrow-circle-right' => '&#xf0a9;',
							'fa-arrow-circle-up' => '&#xf0aa;',
							'fa-arrow-circle-down' => '&#xf0ab;',
							'fa-globe' => '&#xf0ac;',
							'fa-wrench' => '&#xf0ad;',
							'fa-tasks' => '&#xf0ae;',
							'fa-filter' => '&#xf0b0;',
							'fa-briefcase' => '&#xf0b1;',
							'fa-arrows-alt' => '&#xf0b2;',
							'fa-users' => '&#xf0c0;',
							'fa-link' => '&#xf0c1;',
							'fa-cloud' => '&#xf0c2;',
							'fa-flask' => '&#xf0c3;',
							'fa-scissors' => '&#xf0c4;',
							'fa-files-o' => '&#xf0c5;',
							'fa-paperclip' => '&#xf0c6;',
							'fa-floppy-o' => '&#xf0c7;',
							'fa-square' => '&#xf0c8;',
							'fa-bars' => '&#xf0c9;',
							'fa-list-ul' => '&#xf0ca;',
							'fa-list-ol' => '&#xf0cb;',
							'fa-strikethrough' => '&#xf0cc;',
							'fa-underline' => '&#xf0cd;',
							'fa-table' => '&#xf0ce;',
							'fa-magic' => '&#xf0d0;',
							'fa-truck' => '&#xf0d1;',
							'fa-pinterest' => '&#xf0d2;',
							'fa-pinterest-square' => '&#xf0d3;',
							'fa-google-plus-square' => '&#xf0d4;',
							'fa-google-plus' => '&#xf0d5;',
							'fa-money' => '&#xf0d6;',
							'fa-caret-down' => '&#xf0d7;',
							'fa-caret-up' => '&#xf0d8;',
							'fa-caret-left' => '&#xf0d9;',
							'fa-caret-right' => '&#xf0da;',
							'fa-columns' => '&#xf0db;',
							'fa-sort' => '&#xf0dc;',
							'fa-sort-asc' => '&#xf0dd;',
							'fa-sort-desc' => '&#xf0de;',
							'fa-envelope' => '&#xf0e0;',
							'fa-linkedin' => '&#xf0e1;',
							'fa-undo' => '&#xf0e2;',
							'fa-gavel' => '&#xf0e3;',
							'fa-tachometer' => '&#xf0e4;',
							'fa-comment-o' => '&#xf0e5;',
							'fa-comments-o' => '&#xf0e6;',
							'fa-bolt' => '&#xf0e7;',
							'fa-sitemap' => '&#xf0e8;',
							'fa-umbrella' => '&#xf0e9;',
							'fa-clipboard' => '&#xf0ea;',
							'fa-lightbulb-o' => '&#xf0eb;',
							'fa-exchange' => '&#xf0ec;',
							'fa-cloud-download' => '&#xf0ed;',
							'fa-cloud-upload' => '&#xf0ee;',
							'fa-user-md' => '&#xf0f0;',
							'fa-stethoscope' => '&#xf0f1;',
							'fa-suitcase' => '&#xf0f2;',
							'fa-bell-o' => '&#xf0a2;',
							'fa-coffee' => '&#xf0f4;',
							'fa-cutlery' => '&#xf0f5;',
							'fa-file-text-o' => '&#xf0f6;',
							'fa-building-o' => '&#xf0f7;',
							'fa-hospital-o' => '&#xf0f8;',
							'fa-ambulance' => '&#xf0f9;',
							'fa-medkit' => '&#xf0fa;',
							'fa-fighter-jet' => '&#xf0fb;',
							'fa-beer' => '&#xf0fc;',
							'fa-h-square' => '&#xf0fd;',
							'fa-plus-square' => '&#xf0fe;',
							'fa-angle-double-left' => '&#xf100;',
							'fa-angle-double-right' => '&#xf101;',
							'fa-angle-double-up' => '&#xf102;',
							'fa-angle-double-down' => '&#xf103;',
							'fa-angle-left' => '&#xf104;',
							'fa-angle-right' => '&#xf105;',
							'fa-angle-up' => '&#xf106;',
							'fa-angle-down' => '&#xf107;',
							'fa-desktop' => '&#xf108;',
							'fa-laptop' => '&#xf109;',
							'fa-tablet' => '&#xf10a;',
							'fa-mobile' => '&#xf10b;',
							'fa-circle-o' => '&#xf10c;',
							'fa-quote-left' => '&#xf10d;',
							'fa-quote-right' => '&#xf10e;',
							'fa-spinner' => '&#xf110;',
							'fa-circle' => '&#xf111;',
							'fa-reply' => '&#xf112;',
							'fa-github-alt' => '&#xf113;',
							'fa-folder-o' => '&#xf114;',
							'fa-folder-open-o' => '&#xf115;',
							'fa-smile-o' => '&#xf118;',
							'fa-frown-o' => '&#xf119;',
							'fa-meh-o' => '&#xf11a;',
							'fa-gamepad' => '&#xf11b;',
							'fa-keyboard-o' => '&#xf11c;',
							'fa-flag-o' => '&#xf11d;',
							'fa-flag-checkered' => '&#xf11e;',
							'fa-terminal' => '&#xf120;',
							'fa-code' => '&#xf121;',
							'fa-reply-all' => '&#xf122;',
							'fa-mail-reply-all' => '&#xf122;',
							'fa-star-half-o' => '&#xf123;',
							'fa-location-arrow' => '&#xf124;',
							'fa-crop' => '&#xf125;',
							'fa-code-fork' => '&#xf126;',
							'fa-chain-broken' => '&#xf127;',
							'fa-question' => '&#xf128;',
							'fa-info' => '&#xf129;',
							'fa-exclamation' => '&#xf12a;',
							'fa-superscript' => '&#xf12b;',
							'fa-subscript' => '&#xf12c;',
							'fa-eraser' => '&#xf12d;',
							'fa-puzzle-piece' => '&#xf12e;',
							'fa-microphone' => '&#xf130;',
							'fa-microphone-slash' => '&#xf131;',
							'fa-shield' => '&#xf132;',
							'fa-calendar-o' => '&#xf133;',
							'fa-fire-extinguisher' => '&#xf134;',
							'fa-rocket' => '&#xf135;',
							'fa-maxcdn' => '&#xf136;',
							'fa-chevron-circle-left' => '&#xf137;',
							'fa-chevron-circle-right' => '&#xf138;',
							'fa-chevron-circle-up' => '&#xf139;',
							'fa-chevron-circle-down' => '&#xf13a;',
							'fa-html5' => '&#xf13b;',
							'fa-css3' => '&#xf13c;',
							'fa-anchor' => '&#xf13d;',
							'fa-unlock-alt' => '&#xf13e;',
							'fa-bullseye' => '&#xf140;',
							'fa-ellipsis-h' => '&#xf141;',
							'fa-ellipsis-v' => '&#xf142;',
							'fa-rss-square' => '&#xf143;',
							'fa-play-circle' => '&#xf144;',
							'fa-ticket' => '&#xf145;',
							'fa-minus-square' => '&#xf146;',
							'fa-minus-square-o' => '&#xf147;',
							'fa-level-up' => '&#xf148;',
							'fa-level-down' => '&#xf149;',
							'fa-check-square' => '&#xf14a;',
							'fa-pencil-square' => '&#xf14b;',
							'fa-external-link-square' => '&#xf14c;',
							'fa-share-square' => '&#xf14d;',
							'fa-compass' => '&#xf14e;',
							'fa-caret-square-o-down' => '&#xf150;',
							'fa-caret-square-o-up' => '&#xf151;',
							'fa-caret-square-o-right' => '&#xf152;',
							'fa-eur' => '&#xf153;',
							'fa-gbp' => '&#xf154;',
							'fa-usd' => '&#xf155;',
							'fa-inr' => '&#xf156;',
							'fa-jpy' => '&#xf157;',
							'fa-rub' => '&#xf158;',
							'fa-krw' => '&#xf159;',
							'fa-btc' => '&#xf15a;',
							'fa-file' => '&#xf15b;',
							'fa-file-text' => '&#xf15c;',
							'fa-sort-alpha-asc' => '&#xf15d;',
							'fa-sort-alpha-desc' => '&#xf15e;',
							'fa-sort-amount-asc' => '&#xf160;',
							'fa-sort-amount-desc' => '&#xf161;',
							'fa-sort-numeric-asc' => '&#xf162;',
							'fa-sort-numeric-desc' => '&#xf163;',
							'fa-thumbs-up' => '&#xf164;',
							'fa-thumbs-down' => '&#xf165;',
							'fa-youtube-square' => '&#xf166;',
							'fa-youtube' => '&#xf167;',
							'fa-xing' => '&#xf168;',
							'fa-xing-square' => '&#xf169;',
							'fa-youtube-play' => '&#xf16a;',
							'fa-dropbox' => '&#xf16b;',
							'fa-stack-overflow' => '&#xf16c;',
							'fa-instagram' => '&#xf16d;',
							'fa-flickr' => '&#xf16e;',
							'fa-adn' => '&#xf170;',
							'fa-bitbucket' => '&#xf171;',
							'fa-bitbucket-square' => '&#xf172;',
							'fa-tumblr' => '&#xf173;',
							'fa-tumblr-square' => '&#xf174;',
							'fa-long-arrow-down' => '&#xf175;',
							'fa-long-arrow-up' => '&#xf176;',
							'fa-long-arrow-left' => '&#xf177;',
							'fa-long-arrow-right' => '&#xf178;',
							'fa-apple' => '&#xf179;',
							'fa-windows' => '&#xf17a;',
							'fa-android' => '&#xf17b;',
							'fa-linux' => '&#xf17c;',
							'fa-dribbble' => '&#xf17d;',
							'fa-skype' => '&#xf17e;',
							'fa-foursquare' => '&#xf180;',
							'fa-trello' => '&#xf181;',
							'fa-female' => '&#xf182;',
							'fa-male' => '&#xf183;',
							'fa-gittip' => '&#xf184;',
							'fa-sun-o' => '&#xf185;',
							'fa-moon-o' => '&#xf186;',
							'fa-archive' => '&#xf187;',
							'fa-bug' => '&#xf188;',
							'fa-vk' => '&#xf189;',
							'fa-weibo' => '&#xf18a;',
							'fa-renren' => '&#xf18b;',
							'fa-pagelines' => '&#xf18c;',
							'fa-stack-exchange' => '&#xf18d;',
							'fa-arrow-circle-o-right' => '&#xf18e;',
							'fa-arrow-circle-o-left' => '&#xf190;',
							'fa-caret-square-o-left' => '&#xf191;',
							'fa-dot-circle-o' => '&#xf192;',
							'fa-wheelchair' => '&#xf193;',
							'fa-vimeo-square' => '&#xf194;',
							'fa-try' => '&#xf195;',
							'fa-plus-square-o' => '&#xf196;',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_531f06272a6d4',
						'label' => 'Service Name',
						'name' => 'service_name',
						'type' => 'text',
						'instructions' => 'Add the name of the service',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_531f0a622a6d6',
						'label' => 'Service Link',
						'name' => 'service_link',
						'type' => 'text',
						'instructions' => 'Add the link',
						'column_width' => '',
						'default_value' => 'http://',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_531f0a7a2a6d7',
						'label' => 'Short Description',
						'name' => 'short_description',
						'type' => 'text',
						'instructions' => 'Add a short description (category)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_531f0ab22a6d8',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Service',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-service.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_video-post',
		'title' => 'Video Post',
		'fields' => array (
			array (
				'key' => 'field_53231bcebc9a9',
				'label' => 'Video Type',
				'name' => 'video_type',
				'type' => 'radio',
				'instructions' => 'Choose the video type',
				'choices' => array (
					'youtube' => 'YouTube',
					'vimeo' => 'Vimeo',
					'selfhost' => 'Self Hosted',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'youtube',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53231c08bc9aa',
				'label' => 'Video Id',
				'name' => 'video_id',
				'type' => 'text',
				'instructions' => 'Add the video ID',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53231bcebc9a9',
							'operator' => '==',
							'value' => 'youtube',
						),
						array (
							'field' => 'field_53231bcebc9a9',
							'operator' => '==',
							'value' => 'vimeo',
						),
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53231c3bbc9ac',
				'label' => 'Video File',
				'name' => 'video_file',
				'type' => 'file',
				'instructions' => 'Add the video file',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53231bcebc9a9',
							'operator' => '==',
							'value' => 'selfhost',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>